config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    resources :users, only: [:update, :show, :index, :edit]

    resources :lists do
      resources :items
    end

    root to: 'welcome#index'

    get 'about' => 'welcome#about'
end

app/models/item.rb
class Item < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :list
  belongs_to :user

  default_scope { order('created_at ASC')}
  scope :due_soon, -> { where("duedate <= ? ", Date.today + 3 ) }

  validates :name, length: { minimum: 5}

  def days_left
    (duedate.to_date - Date.today).to_i
  end

  def due_soon
    if ((duedate.to_date - DateTime.now.to_date).to_i <= 2)
    end
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :title, length: {minimum: 5}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #:lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :list
  has_many :items

  def items_due_soon
    items.due_soon
  end

  def score
    items.only_deleted.count - items.count
  end

  def self.by_score
    all.sort_by { |user| user.score }.reverse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    rescue_from Pundit::NotAuthorizedError do |exception|
      redirect_to root_url, alert: exception.message
    end

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :html, :js

  def index
    @item = current_user.item.all
  end


  def create
    @list = List.find(params[:list_id])
    @item = current_user.items.build(item_params)
    @item.list = @list
    @new_item = Item.new

    if @item.save
      flash[:notice]= "Item was saved."
      redirect_to @list
    else
      flash[:error] = "Error saving item. Please try again."
      redirect_to @list
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @item = Item.find(params[:id])
  end

  def update
    @list = List.find(params[:list_id])
    @item = Item.find(params[:id])

    if @item.update_attributes(item_params)
      flash[:notice]= "Item was updated"
      redirect_to @list
    else
      flash[:error] = "Error updating item.  Please try again."
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @item = @list.items.find(params[:id])
    authorize @item

    if @item.destroy
      flash[:notice] = "Item was completed"
    else
      flash[:error] = "Item could not be completed successufully. Please try again."
    end
      respond_with(@item) do |format|
        format.html { redirect_to @list }
      end
  end

  private

  def item_params
    params.require(:item).permit(:name, :duedate)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  respond_to :html, :js

  def create
    @list = current_user.list.build(list_params) #Wouldn't need authorize if i have current user create it?
    authorize @list
    if @list.save
      flash[:notice] = "List was saved"
      redirect_to @list
    else
      flash[:error] = "There was an error saving the To-do List. Please try again."
      render :new
    end
  end

  def index
    if current_user
      @lists = current_user.list.all #is this the correct way to dispaly all ?
    else
      flash[:error] = "Make sure you are signed in and create a new list"
      redirect_to root_path
    end
  end

  def show
    @list = List.find(params[:id])
    authorize @list
    @items = @list.items
    # @item = Item.new
  end

  def new
    @list = List.new
    authorize @list
  end


  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    if @list.update_attributes(list_params)
      flash[:notice] = "List was updated."
      redirect_to @list
    else
      flash[:error] = "Error updating List, Please try again."
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])

    if @list.destroy
      flash[:notice] = "Your list was deleted successfully."
      redirect_to lists_path
    else
      flash[:error] = "There was an error deleting the list."
      redirect_to @list
    end
  end

private

  def list_params
    params.require(:list).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.by_score
  end

  def show
    @user = User.find(params[:id])
    @list = @user.list
    @items = @user.items.sort_by(&:duedate)
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end
  end

private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<% if current_user %>

<h3>Add a To-Do</h3>
<div class="row">
  <div class="col-md-8">
  <%= form_for [list, list.items.new], method: :create do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, class: "form-control" %>
      <%= f.label :due  %>
      <%= f. datetime_select :duedate, order: [:month, :day, :year], start_year: Date.today.year, discard_minute: true, discard_hour: true %>
    </div>
    <div class="form-group">
      <%= f.submit "Add Item", class: "btn btn-success" %>
    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/items/_item.html.erb
<tr class="media" id="item-<%= item.id %>" >
  <% if item.name!=nil %> <!-- Always had one extra check mark -->
    <td><%= link_to [item.list, item], method: :delete, remote: true do %>
      <i class="fa fa-check-square-o fa-2x"></i>
    <% end %>
    </td>
  <% end %>
    <td><h3><%= item.name %></h3></td>
    <td><h3><%= item.days_left %></h3></td>
    <td><h3><%= link_to "Edit", edit_list_item_path(@list, item) %></h3></td>
</tr>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
$('#item-' +<%= @item.id %>).hide();
<% else %>
  $('#item-' +<%= @item.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
<% end %>

app/views/items/edit.html.erb
<h1><%= @item.name %></h1>
<div class="row">
  <div class="col-md-8">
    <%= form_for [@list, @item] do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: "Item name" %>
      <%= f.label :duedate  %>
      <%= f. datetime_select :duedate, order: [:month, :day, :year], start_year: Date.today.year, discard_minute: true, discard_hour: true %>
    </div>
    <div class="form-group">
      <%= f.submit "Update", class: "btn btn-success" %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class= "footer" >
  <i class="fa fa-copyright fa-lg"> 2015</i>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Lists", lists_path %></li>
        <li><%= link_to "Users", users_path %></li>

     <div class="pull-right user-info">
          <% if current_user %>
              Hello <%= link_to (current_user.name || current_user.email), current_user %>! <span class= "badge"> <%= current_user.score %> </span>
              <%= link_to edit_user_registration_path, class: 'btn btn-info btn-sm' do %>
                <span class= "glyphicon glyphicon-user"></span>
              <% end %>

                <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-warning btn-sm' do  %>
                  <span class="glyphicon glyphicon-log-out"></span>
                <% end %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path %>
          <% end %>
        </div>
      </ul>



       <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

      <%= yield %>
    </div>
    <div class="container">
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/lists/_list.html.erb
<div class= "media">
  <div class= "media-body">
    <h4 class= "media-heading">
      <%= link_to (list.title), [@list] %>
    </h4>
      <small>
        submitted <%= time_ago_in_words(list.created_at) %> ago by
        <%= list.user.name %><br/>
        <%= list.items.count %> Items
      </small>
  </div>
</div>

app/views/lists/edit.html.erb
<h1><%= @list.title %></h1>
<div class="row">
  <div class="col-md-8">
  <%= form_for @list do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "List Title" %>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: "btn btn-success" %>
    </div>
  <% end %>
  </div>
</div>

app/views/lists/index.html.erb
<table class="table">
  <caption> <h1>My To-Do Lists<span class="pull-right"><%= link_to "New List", new_list_path, class: 'btn btn-success btn-lg' %></span></h1></caption>
  <br/>
  <tr>
    <th><h3>List</h3></th>
    <th><h3>Tasks Left</h3></th>
    <th><h3>Delete List</h3></th>
  </tr>
    <% @lists.each do |list| %>
  <tr>
   <td><h3><%= link_to list.title, list %></h3></td>
   <td><h3><%= pluralize(list.items.count, 'item') %></h3></td>
   <td align="justify"> <%= link_to "Delete", list, method: :delete, data: {confirm: "Are you sure you want to delete this List?"}, class: 'btn btn-danger btn-lg' %></td>
  </tr>
    <% end %>
</table>

app/views/lists/new.html.erb
<h1>New To-do List</h1>
<div class="row">
  <div class="col-md-8">
  <%= form_for @list do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "List Title" %>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: "btn btn-success" %>
    </div>
  <% end %>

app/views/lists/show.html.erb
<br/>
<table class= "table">
  <h1><%= @list.title %>
    <span class="pull-right">
      <%= link_to "Edit List", edit_list_path, class: "btn btn-success" %>
      <%= link_to "Delete List", @list, method: :delete,  class: "btn btn-danger", data: { confirm: 'Are you sure you want to delete this list?'} %>
    </span>
  </h1>

    <tr>
      <th><h3>Completed</h3></th>
      <th><h3>Task To-Do</h3></th>
      <th><h3>Days Left</h3></th>
    </tr>
    <%= render @items %>
</table>
    <%= render partial: 'items/form', locals: {list: @list} %>

app/views/users/_user.html.erb
<tr>
    <td><h3><%= user_counter +1 %></h3></td>
    <td><h3><%= user.name %></h3></td>
    <td><h3><%= user.score %></h3></td>
</tr>

app/views/users/index.html.erb
<table class="table">
  <caption>
    <h1>Productive Users </h1>
    <p class= "lead">
      See where you rank among fellow Blocitoff users.  The only way to reach the top is to start completing To-do's Today!
    </p>
     </caption>
  <br/>

  <tr>
    <th><h3>Rank</h3></th>
    <th><h3>User</h3></th>
    <th><h3>Score</h3></th>
  </tr>

     <%= render partial: 'users/user', collection: @users %>
</table>

app/views/users/show.html.erb
<div class= "row">
  <div class= "col-md-8">
    <br/>
    <h1><%= @user.name %></h1>
    <h3> Score: <%= @user.score %> </h3>
    <p>
      User score helps show productivity: <br/>
      Based on How many To-do's completed - How many To-do's Left to complete.
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <div class="tabbable tabs-left">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#lists" data-toggle="tab">Lists  <span><%= @user.list.count %></span></a></li>
        <li><a href="#items" data-toggle="tab">To-Do's  <span><%= @user.items.count %></span></a></li>
      </ul>
      <div class="tab-content">
      <div class="tab-pane active" id="lists">
        <% @list.each do |list| %>
          <h3><%= link_to list.title, list %></h3>
        <% end %>
      </div>
      <div class="tab-pane" id="items">
        <% @items.each do |item| %>
          <h3><%= item.name.capitalize %> <small><%= item.days_left %> days left</small></h3>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/about.html.erb
<div class="jumbotron" id="about">
  <h1>THINGS TO DO?</h1>
    <p class= "lead" >
      Blocitoff is here to help you! Create custom to-do lists,
      add individual tasks with due dates, mark completed with auto delte, and If things get
      busy, email friendly reminders of tasks due soon. Also help track productivity with a
      user score based on tasks to-do vs tasks completed. Get things done Today.
    </p>
    <% if current_user %>
      <%= link_to "Creat a List", new_list_path, class: 'btn btn-primary btn-lg' %>
    <% else %>
      <%= link_to "Sign Up NOW", new_user_registration_path, class: 'btn btn-primary btn-lg' %>
    <% end %>
</div>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <h1>Blocitoff</h1>
  <p>Things to do?  Blocitoff helps organize your busy life into simple to do lists. Start Checking things off Today!</p>
  <% if current_user %>
    <p>
      <%= link_to "New To-do List", new_list_path, class: 'btn btn-success btn-lg' %>
  <% else %>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
    </p>
  <% end %>
</div>

<div class="row" id="bpoints">
  <div class="col-md-4">
    <h2>Create</h2>
    <span class= "glyphicon glyphicon-pencil"></span>
    <p>Make simple todo lists for anything in your life.</p>
  </div>
  <div class="col-md-4">
    <h2>Prioritize</h2>
    <span class= "glyphicon glyphicon-bell"></span>
    <p>Set importance and due dates for each item of your list.</p>
  </div>
  <div class="col-md-4">
    <h2>Accomplish</h2>
    <span class= "glyphicon glyphicon-ok"></span>
    <p>Finish a task and delete it from your list.</p>
  </div>